DROP TABLE IF EXISTS `ai_model_provider`;
CREATE TABLE `ai_model_provider` (
                                     `id` BIGINT NOT NULL COMMENT '主键ID',
                                     `provider_code` VARCHAR(50) NOT NULL COMMENT '供应商编码（如：OPENAI、AZURE_OPENAI、OLLAMA、QWEN、ERNIE）',
                                     `provider_name` VARCHAR(100) NOT NULL COMMENT '供应商名称（如：OpenAI、Azure OpenAI、Ollama、通义千问、文心一言）',
                                     `provider_icon` VARCHAR(255) DEFAULT NULL COMMENT '供应商图标URL',
                                     `description` VARCHAR(500) DEFAULT NULL COMMENT '供应商描述',
                                     `default_endpoint` VARCHAR(500) DEFAULT NULL COMMENT '默认API端点',
                                     `supports_streaming` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否支持流式输出：0-否 1-是',
                                     `supports_vision` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否支持视觉能力：0-否 1-是',
                                     `supports_function_call` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否支持函数调用：0-否 1-是',
                                     `auth_type` VARCHAR(20) NOT NULL DEFAULT 'API_KEY' COMMENT '认证类型：API_KEY、BEARER_TOKEN、CUSTOM',
                                     `config_template` TEXT DEFAULT NULL COMMENT '配置模板（JSON格式，定义该供应商需要的配置项）',
                                     `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
                                     `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序号',
                                     `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建者',
                                     `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新者',
                                     `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                     `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0-未删除 1-已删除',
                                     `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
                                     PRIMARY KEY (`id`),
                                     UNIQUE KEY `uk_provider_code` (`provider_code`),
                                     KEY `idx_status` (`status`),
                                     KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI模型供应商表';

DROP TABLE IF EXISTS `ai_model_config`;
CREATE TABLE `ai_model_config` (
                                   `id` BIGINT NOT NULL COMMENT '主键ID',
                                   `config_name` VARCHAR(100) NOT NULL COMMENT '配置名称（用户自定义）',
                                   `user_id` BIGINT NOT NULL COMMENT '用户ID（配置所属用户）',
                                   `provider_id` BIGINT NOT NULL COMMENT '供应商ID，关联ai_model_provider.id',
                                   `provider_code` VARCHAR(50) NOT NULL COMMENT '供应商编码（冗余字段，便于查询）',
                                   `model_name` VARCHAR(100) NOT NULL COMMENT '模型名称（如：gpt-4o、qwen-turbo等）',
                                   `model_alias` VARCHAR(100) DEFAULT NULL COMMENT '模型别名（用户自定义显示名称）',
                                   `api_key` VARCHAR(500) NOT NULL COMMENT 'API密钥（AES加密存储）',
                                   `api_endpoint` VARCHAR(500) DEFAULT NULL COMMENT 'API端点地址（覆盖默认端点）',
                                   `extra_config` TEXT DEFAULT NULL COMMENT '扩展配置（JSON格式，如：deploymentName、secretKey等）',
                                   `temperature` DECIMAL(3,2) DEFAULT 0.70 COMMENT '温度参数（0.00-2.00），控制输出随机性',
                                   `max_tokens` INT DEFAULT 4096 COMMENT '最大输出Token数',
                                   `top_p` DECIMAL(3,2) DEFAULT 1.00 COMMENT 'Top-P采样参数',
                                   `frequency_penalty` DECIMAL(3,2) DEFAULT 0.00 COMMENT '频率惩罚参数',
                                   `presence_penalty` DECIMAL(3,2) DEFAULT 0.00 COMMENT '存在惩罚参数',
                                   `timeout_seconds` INT DEFAULT 60 COMMENT '请求超时时间（秒）',
                                   `max_retries` INT DEFAULT 3 COMMENT '最大重试次数',
                                   `is_default` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认模型：0-否 1-是',
                                   `is_streaming_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用流式输出：0-否 1-是',
                                   `daily_quota` INT DEFAULT NULL COMMENT '每日调用限额（次数），NULL表示无限制',
                                   `monthly_quota` INT DEFAULT NULL COMMENT '每月调用限额（次数），NULL表示无限制',
                                   `token_quota` BIGINT DEFAULT NULL COMMENT 'Token总量限额，NULL表示无限制',
                                   `used_count` BIGINT NOT NULL DEFAULT 0 COMMENT '累计调用次数',
                                   `used_tokens` BIGINT NOT NULL DEFAULT 0 COMMENT '累计使用Token数',
                                   `last_used_time` DATETIME DEFAULT NULL COMMENT '最后使用时间',
                                   `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
                                   `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建者',
                                   `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新者',
                                   `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                   `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0-未删除 1-已删除',
                                   `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
                                   PRIMARY KEY (`id`),
                                   KEY `idx_user_id` (`user_id`),
                                   KEY `idx_provider_id` (`provider_id`),
                                   KEY `idx_provider_code` (`provider_code`),
                                   KEY `idx_model_name` (`model_name`),
                                   KEY `idx_status` (`status`),
                                   KEY `idx_is_default` (`is_default`),
                                   KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI模型配置表';

DROP TABLE IF EXISTS `ai_chat_log`;
CREATE TABLE `ai_chat_log` (
                               `id` BIGINT NOT NULL COMMENT '主键ID',
                               `trace_id` VARCHAR(64) NOT NULL COMMENT '追踪ID（用于链路追踪）',
                               `config_id` BIGINT NOT NULL COMMENT '模型配置ID，关联ai_model_config.id',
                               `provider_code` VARCHAR(50) NOT NULL COMMENT '供应商编码',
                               `model_name` VARCHAR(100) NOT NULL COMMENT '使用的模型名称',
                               `user_id` BIGINT DEFAULT NULL COMMENT '调用用户ID',
                               `username` VARCHAR(64) DEFAULT NULL COMMENT '调用用户名',
                               `session_id` VARCHAR(64) DEFAULT NULL COMMENT '会话ID（同一对话多轮）',
                               `conversation_id` VARCHAR(64) DEFAULT NULL COMMENT '对话ID',
                               `request_type` VARCHAR(20) NOT NULL DEFAULT 'CHAT' COMMENT '请求类型：CHAT-对话、COMPLETION-补全、EMBEDDING-向量化',
                               `request_content` TEXT NOT NULL COMMENT '请求内容（用户输入）',
                               `request_tokens` INT DEFAULT NULL COMMENT '请求Token数',
                               `response_content` LONGTEXT DEFAULT NULL COMMENT '响应内容（AI输出）',
                               `response_tokens` INT DEFAULT NULL COMMENT '响应Token数',
                               `total_tokens` INT DEFAULT NULL COMMENT '总Token数',
                               `is_streaming` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否流式请求：0-否 1-是',
                               `response_status` VARCHAR(20) NOT NULL COMMENT '响应状态：SUCCESS-成功、FAILED-失败、TIMEOUT-超时',
                               `error_code` VARCHAR(50) DEFAULT NULL COMMENT '错误码',
                               `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
                               `latency_ms` BIGINT NOT NULL COMMENT '响应耗时（毫秒）',
                               `first_token_latency_ms` INT DEFAULT NULL COMMENT '首Token延迟（毫秒，流式场景）',
                               `cost_amount` DECIMAL(10,6) DEFAULT NULL COMMENT '费用金额（美元）',
                               `input_unit_price` DECIMAL(10,6) DEFAULT NULL COMMENT '输入Token单价（美元/千Token）',
                               `output_unit_price` DECIMAL(10,6) DEFAULT NULL COMMENT '输出Token单价（美元/千Token）',
                               `client_ip` VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
                               `user_agent` VARCHAR(500) DEFAULT NULL COMMENT '用户代理',
                               `request_time` DATETIME NOT NULL COMMENT '请求时间',
                               `response_time` DATETIME DEFAULT NULL COMMENT '响应时间',
                               `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               PRIMARY KEY (`id`),
                               UNIQUE KEY `uk_trace_id` (`trace_id`),
                               KEY `idx_config_id` (`config_id`),
                               KEY `idx_provider_code` (`provider_code`),
                               KEY `idx_user_id` (`user_id`),
                               KEY `idx_session_id` (`session_id`),
                               KEY `idx_conversation_id` (`conversation_id`),
                               KEY `idx_response_status` (`response_status`),
                               KEY `idx_request_time` (`request_time`),
                               KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI调用日志表';

DROP TABLE IF EXISTS `ai_conversation`;
CREATE TABLE `ai_conversation` (
                                   `id` BIGINT NOT NULL COMMENT '主键ID',
                                   `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
                                   `user_id` BIGINT NOT NULL COMMENT '用户ID',
                                   `config_id` BIGINT NOT NULL COMMENT '模型配置ID',
                                   `title` VARCHAR(200) DEFAULT NULL COMMENT '会话标题（自动生成或用户自定义）',
                                   `system_prompt` TEXT DEFAULT NULL COMMENT '系统提示词',
                                   `message_count` INT NOT NULL DEFAULT 0 COMMENT '消息数量',
                                   `total_tokens` BIGINT NOT NULL DEFAULT 0 COMMENT '累计Token数',
                                   `total_cost` DECIMAL(10,4) DEFAULT 0.0000 COMMENT '累计费用（美元）',
                                   `last_message_time` DATETIME DEFAULT NULL COMMENT '最后消息时间',
                                   `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-已归档 1-活跃',
                                   `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                   `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0-未删除 1-已删除',
                                   PRIMARY KEY (`id`),
                                   UNIQUE KEY `uk_conversation_id` (`conversation_id`),
                                   KEY `idx_user_id` (`user_id`),
                                   KEY `idx_config_id` (`config_id`),
                                   KEY `idx_status` (`status`),
                                   KEY `idx_last_message_time` (`last_message_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI会话表';

DROP TABLE IF EXISTS `ai_conversation_message`;
CREATE TABLE `ai_conversation_message` (
                                           `id` BIGINT NOT NULL COMMENT '主键ID',
                                           `message_id` VARCHAR(64) NOT NULL COMMENT '消息ID',
                                           `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
                                           `role` VARCHAR(20) NOT NULL COMMENT '角色：USER-用户、ASSISTANT-助手、SYSTEM-系统',
                                           `content` TEXT NOT NULL COMMENT '消息内容',
                                           `tokens` INT DEFAULT NULL COMMENT 'Token数',
                                           `parent_message_id` VARCHAR(64) DEFAULT NULL COMMENT '父消息ID（用于消息树结构）',
                                           `log_id` BIGINT DEFAULT NULL COMMENT '关联的日志ID',
                                           `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                           PRIMARY KEY (`id`),
                                           UNIQUE KEY `uk_message_id` (`message_id`),
                                           KEY `idx_conversation_id` (`conversation_id`),
                                           KEY `idx_role` (`role`),
                                           KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI会话消息表';